#DEV enviroment
app:
  message: This is the property file to the ${spring.application.name} DEV

server:
    port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2mem:db;DB_CLOSE_DELAY=1
    username: sa
    password: sa
